
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Label label1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Entry txtStatement;

	private global::Gtk.Button btnRecognize;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Ingrese La Oracion A Reconocer");
		this.vbox1.Add(this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.txtStatement = new global::Gtk.Entry();
		this.txtStatement.CanFocus = true;
		this.txtStatement.Name = "txtStatement";
		this.txtStatement.IsEditable = true;
		this.txtStatement.InvisibleChar = '•';
		this.hbox1.Add(this.txtStatement);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.txtStatement]));
		w2.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnRecognize = new global::Gtk.Button();
		this.btnRecognize.CanFocus = true;
		this.btnRecognize.Name = "btnRecognize";
		this.btnRecognize.UseUnderline = true;
		this.btnRecognize.Label = global::Mono.Unix.Catalog.GetString("Identificar");
		this.hbox1.Add(this.btnRecognize);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnRecognize]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 706;
		this.DefaultHeight = 569;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnRecognize.Clicked += new global::System.EventHandler(this.btnAction);
	}
}
